#!/bin/sh
# $Id: fontName2LaTeX,v 1.5 2007/06/15 13:55:16 mgn Exp $
SRC=$1
DEST=$2
EXT=$3

copyifolder() {

    if [ -f $1 ] ; then
       if [ ! -r $2  ] ; then
          cp $1  $2
       elif [ $1 -nt $2 ] ; then
          cp $1  $2
       fi
    fi
}

copyifolder $SRC/LinLibertine_Re-*.$EXT    $DEST/fxlr.$EXT
copyifolder $SRC/LinLibertine_Bd-*.$EXT    $DEST/fxlb.$EXT
copyifolder $SRC/LinLibertine_BI-*.$EXT    $DEST/fxlbi.$EXT
copyifolder $SRC/LinLibertine_It-*.$EXT    $DEST/fxlri.$EXT
copyifolder $SRC/LinLibertineC_Re-*.$EXT   $DEST/fxlrc.$EXT
copyifolder $SRC/Biolinum_Re-*.$EXT        $DEST/fxbr.$EXT
copyifolder $SRC/Biolinum_Bd-*.$EXT        $DEST/fxbb.$EXT

#copyifolder $SRC/LinLibertineU_Re-*.$EXT   $DEST/fxlru.$EXT

