#!/bin/bash
FILE=$1
OUT=$2
echo "%" >$OUT
while read line; do
   t1=`echo $line | sed 's/0x\(.*\) \(.*\)/\1/g'`
   t2=`echo $line | sed 's/0x\(.*\) \(.*\)/\2/g'`
   echo "\\alias{$t1}{$((0x$t1))}{$t2}" >>$OUT
done < $FILE
echo "\\endinput" >>$OUT
